use_frameworks!

platform :ios, '12.1'

target 'SALIMALYASICurved_Example' do
  pod 'SALIMALYASICurved', :path => '../'
  target 'SALIMALYASICurved_Tests' do
    inherit! :search_paths

    
  end
end
